### ISSUE TITLE
No performance improvement in heat equation benchmark

### ISSUE THREAD

**Issue by fjarri** [bh107/bohrium#19]
(I am sorry for opening so many issues at once)

I am running a heat equation benchmark from the Benchpress suite: [numpy version](https://github.com/bh107/benchpress/blob/master/benchmarks/heat_equation/python_numpy/dep/pure_numpy.py), [bohrium version](https://github.com/bh107/benchpress/blob/master/benchmarks/heat_equation/python_numpy/dep/bohrium_numpy.py) with witdth 2000 and 40 iterations. The Bohrium time is slightly worse than numpy time: 3.49s against 3.34s. Do you have any suggestions on how I might debug this? Could it be connected to [this issue](https://github.com/bh107/bohrium/issues/17)?

**Comment by kenkendk** [comment]
No need to be sorry; that someone cares enough to take the time to open an issue is usually a good sign :).

The Clang compiler used on OSX does not support OpenMP, meaning that you will only get single-core execution on OSX. The work seems to be complete, but so far Apple has not included this in their compiler: https://clang-omp.github.io/

Another issue is that @safl is currently working on the JIT compiler. You can try to enable the JIT compiler and other features, as described here: 
https://bohrium.readthedocs.org/users/config.html#environment-variables

I am unsure how much of it works when there is no OpenMP support though.

**Comment by fjarri** [comment]
Still though, even if the execution is single-threaded, shouldn't it give some performance gain as compared to pure `numpy`, just by removing Python overhead? Also, what about OpenCL - I remember `cmake` said it was found. Is there anything I should enable in the config to turn it on?

**Comment by kenkendk** [comment]
The problem with heat-equation (and vector based approaches, such as NumPy and Bohrium in general) is that they are memory bound.

When you perform `c = a + b + a + b`, you are essentially performing:
```
t0 = a+b
t1 = t0 + a
c = t1 + b
```

This means that for an array of size `n` you need to read `n * 6` memory locations and write `n * 3` locations, giving `9` memory access for only `3` additions. Since the CPU is very fast, it will essentially always wait for memory. Even with multiple cores, you only get a minor speedup as you are still memory bound.

The JIT compilation (and approaches such as: array contraction, streaming operation reorder, etc) solve these issues and can reduce the memory overhead and increase the computational overhead, so you are not waiting for memory, and thus benefit from more CPU cores. We are working on many of these solutions.

The overhead in NumPy itself is fairly low, as most operations are written in C anyway. Bohrium does have some memory management tricks that are not used in NumPy, so you should get some speedup though, but it is possible that NumPy on OSX works differently than on Linux.

OpenCL is used for GPU support, it _should_ work on OSX, but I have not tested it.

**Comment by safl** [comment]
In relation to that. I just updated the docs about the config and env-vars, they were deprecated.

Fusion is by default disabled in the cpu-engine for various reasons.
However, you can enable fusion with array-contraction by setting "jit_level" to 3.
This can be done either via config-file or env-var BH_CPU_JIT_LEVEL="3".
