### ISSUE TITLE
Write an float64 bohrium array into an float64 numpy array gives segmenetation fault

### ISSUE THREAD

**Issue by Ektorus** [bh107/bohrium#4]
The following code:
```python
import numpy as np
import bohrium as bh

a = bh.arange(10000, dtype=bh.float64)
b = np.empty(10000, dtype=np.float64)
print a.dtype, b.dtype

b[:] = a[:]
print "Done"
```
Gives segementation fault.

**Comment by madsbk** [comment]
I cannot reproduce the seg fault on my machine with a fresh checkout. 
But I do get a "RuntimeWarning: Encountering an operation not supported by Bohrium. It will be handled by the original NumPy." warning, which is expected since NumPy will handle the copy.
In order to avoid this warning, please convert `a` to NumPy like:  `b[:] = bh.array(a, bohrium=False)`, or something similar.

**Comment by Ektorus** [comment]
I can confirm that this no longer causes a segmentation fault in the newest version, but merely a warning.
