### ISSUE TITLE
Can I iterate over arrays with do_while?

### ISSUE THREAD

**Issue by dionhaefner** [bh107/bohrium#463]
The following doesn't work:

```python
a = np.zeros([10])
b = [0]
def test(a, b):
    i = b[0]
    a[i:i+1] += 1
    b[0] += 1
np.do_while(test, 10, a, b)
```

The resulting value of `a` is just `array([ 10.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.])`. Is there a way to increment an integer with every iteration, so I can iterate over an axis?

**Comment by madsbk** [comment]
No, not right now. 
My plan is to support a new special Python iterator that can create new views in a predictable way. 

The problem is that the act of create a view (eg. `a[i:i+1]`) often takes longer than running the a single iteration thus we have to include the view manipulation in the JIT compiled kernels.

**Comment by dionhaefner** [comment]
That would be helpful, especially to create custom reductions and accumulations. 👍

**Comment by skjoenberg** [comment]
It is not yet possible to use an index from an array that changes between iterations of the loop. But, the functionality of the above example can be emulated using iterators:
```python
a = np.zeros([10])
def test(a):
    i = get_iterator()
    a[i] += 1
np.do_while(test, 10, a)
```
The resulting value of a is `array([ 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])`.
